language: c

os:
  - linux

addons:
  apt:
    packages:
      - libbsd-dev
      - libarchive-dev
      - libssl-dev
      - liblzma-dev
      - liblua5.2-dev

sudo: required

compiler:
  - clang
  - gcc

before_install:
  - scripts/install_deps.sh

before_script:
  - autoreconf -i

script:
  - scripts/travis_build.sh

after_failure:
  - kyua report --verbose

notifications:
  email: false
